apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ggoods-webapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - ggoods.io
    - '*.ggoods.io'
    secretName: tls-secret
  rules:
  - host: ${ENVIRONMENT_PREFIX}.ggoods.io
    http:
      paths:
        - path: /
          backend:
            serviceName: ggoods-webapp
            servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ggoods-hasura-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - graphql.ggoods.io
    - '*graphql.ggoods.io'
    secretName: tls-secret
  rules:
  - host: graphql.ggoods.io
    http:
      paths:
        - path: /
          backend:
            serviceName: ggoods-hasura
            servicePort: 8080
